### PR TITLE
Update ufpdf.php

### PR DESCRIPTION
**Pull request by rannien**
php7.4 linting warning fixes

### CODE REVIEW

**Review by tawfekov — CHANGES_REQUESTED** [review]
you want to remove my name ? why ?

**Comment by rannien** [comment]
Sorry, I didn't intend to, I created a fork to use that, while you are not accepting my original pull request, but I forget that the pull request was made from the master, and I already changed a bit of composer.json.

I revert it to the original, but could you please accept my merge request about the other compatibility changes I made?

**Comment by rannien** [comment]
I created another pull request that only contains changes about the wrong code: https://github.com/tawfekov/ar-php/pulls

**Comment by tawfekov** [comment]
@rannien I just merged #15 as per your request 

Thank you for your contribution

**Pull request closed without merging**
