### PR TITLE
fix: add extra checking

### PR DESCRIPTION
**Pull request by AidasK**

### CODE REVIEW

**Comment by tawfekov** [comment]
I'm okay with this change , just for curiosity can  how its  exactly failing ?

**Comment by AidasK** [comment]
I just saw this in a stacktrace and this is crashing a whole app for me. So it is better a wrong translation than a 500 page.

**Comment by AidasK** [comment]
Undefined offset: -1
....
  File "/var/www/current/beta/vendor/ar-php/ar-php/I18N/Arabic/Glyphs.php", line 518, in utf8Glyphs
    $output = $this->preConvert($output);
  File "/var/www/current/beta/vendor/ar-php/ar-php/I18N/Arabic/Glyphs.php", line 281, in preConvert
    if (mb_strpos($this->_prevLink, $chars[$i - 2]) !== false) {
  File "/var/www/current/beta/vendor/ar-php/ar-php/I18N/Arabic/Glyphs.php", line 281, in handleError
    if (mb_strpos($this->_prevLink, $chars[$i - 2]) !== false) {
....

**Comment by tawfekov** [comment]
Thank you @AidasK

**Pull request merged**
